---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: hccm-openshift-persistentvolumeclaim
spec:
  columns:
    - name: report_period_start
      type: timestamp
      unit: date
    - name: report_period_end
      type: timestamp
      unit: date
    - name: interval_start
      type: timestamp
      unit: date
    - name: interval_end
      type: timestamp
      unit: date
    - name: namespace
      type: string
      unit: kubernetes_namespace
    - name: persistentvolumeclaim
      type: string
      unit: kubernetes_persistentvolumeclaim
    - name: persistentvolume
      type: string
      unit: kubernetes_persistentvolume
    - name: storageclass
      type: string
      unit: kubernetes_storageclass
    - name: persistentvolumeclaim_capacity_bytes
      type: double
      unit: bytes
    - name: persistentvolumeclaim_capacity_byte_seconds
      type: double
      unit: byte_seconds
    - name: volume_request_storage_byte_seconds
      type: double
      unit: byte_seconds
    - name: persistentvolumeclaim_usage_byte_seconds
      type: double
      unit: byte_seconds
  inputs:
    - name: ReportingStart
    - name: ReportingEnd
  query: |
    WITH cte_hourly_persistentvolumeclaim_capacity AS (
      SELECT date_trunc('hour', "timestamp") as interval_start,
        namespace,
        persistentvolumeclaim,
        max(persistentvolumeclaim_capacity_bytes) as persistentvolumeclaim_capacity_bytes,
        sum(persistentvolumeclaim_capacity_byte_seconds) as persistentvolumeclaim_capacity_byte_seconds
      FROM {| generationQueryViewName "persistentvolumeclaim-capacity-raw" |}
      WHERE "timestamp" >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
        AND "timestamp" < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
        AND dt >= '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prometheusMetricPartitionFormat |}'
        AND dt <= '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prometheusMetricPartitionFormat |}'
      GROUP BY namespace, persistentvolumeclaim, date_trunc('hour', "timestamp")
    ),
    cte_hourly_persistentvolumeclaim_requests AS (
      SELECT date_trunc('hour', "timestamp") as interval_start,
        namespace,
        persistentvolumeclaim,
        max(persistentvolume) as persistentvolume,
        max(storageclass) as storageclass,
        sum(volume_request_storage_byte_seconds) as volume_request_storage_byte_seconds
      FROM {| generationQueryViewName "persistentvolumeclaim-request-raw" |}
      WHERE "timestamp" >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
        AND "timestamp" < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
        AND dt >= '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prometheusMetricPartitionFormat |}'
        AND dt <= '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prometheusMetricPartitionFormat |}'
      GROUP BY namespace, persistentvolumeclaim, date_trunc('hour', "timestamp")
    ),
    cte_hourly_persistentvolumeclaim_usage AS (
      SELECT date_trunc('hour', "timestamp") as interval_start,
        namespace,
        persistentvolumeclaim,
        sum(persistentvolumeclaim_usage_byte_seconds) as persistentvolumeclaim_usage_byte_seconds
      FROM {| generationQueryViewName "persistentvolumeclaim-usage-raw" |}
      WHERE "timestamp" >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
        AND "timestamp" < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
        AND dt >= '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prometheusMetricPartitionFormat |}'
        AND dt <= '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prometheusMetricPartitionFormat |}'
      GROUP BY namespace, persistentvolumeclaim, date_trunc('hour', "timestamp")
    )
    SELECT
      date_trunc('month', timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}') AS report_period_start,
      date_trunc('month', timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}')  + interval '1' month - interval '1' second AS report_period_end,
      PVCU.interval_start,
      PVCU.interval_start + interval '59' minute + interval '59' second as interval_end,
      PVCU.namespace,
      PVCU.persistentvolumeclaim,
      PVCR.persistentvolume,
      PVCR.storageclass,
      PVCC.persistentvolumeclaim_capacity_bytes,
      PVCC.persistentvolumeclaim_capacity_byte_seconds,
      PVCR.volume_request_storage_byte_seconds,
      PVCU.persistentvolumeclaim_usage_byte_seconds
    FROM cte_hourly_persistentvolumeclaim_usage AS PVCU
    JOIN cte_hourly_persistentvolumeclaim_requests AS PVCR
        ON PVCU.namespace = PVCR.namespace
          AND PVCU.persistentvolumeclaim = PVCR.persistentvolumeclaim
          AND PVCU.interval_start = PVCR.interval_start
    JOIN cte_hourly_persistentvolumeclaim_capacity AS PVCC
        ON PVCU.namespace = PVCC.namespace
          AND PVCU.persistentvolumeclaim = PVCC.persistentvolumeclaim
          AND PVCU.interval_start = PVCC.interval_start
  reportQueries:
    - persistentvolumeclaim-capacity-raw
    - persistentvolumeclaim-request-raw
    - persistentvolumeclaim-usage-raw
  view:
    disabled: true
