---
apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  labels:
    cost-management: "true"
  name: hccm-openshift-usage
spec:
  query: hccm-openshift-usage
  schedule:
    period: hourly
