---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportQuery
metadata:
  labels:
    cost-management: "true"
  name: hccm-openshift-persistentvolumeclaim-lookback
spec:
  view:
    disabled: true
  columns:
    - name: report_period_start
      type: timestamp
      unit: date
    - name: report_period_end
      type: timestamp
      unit: date
    - name: interval_start
      type: timestamp
      unit: date
    - name: interval_end
      type: timestamp
      unit: date
    - name: namespace
      type: varchar
      unit: kubernetes_namespace
    - name: pod
      type: varchar
      unit: kubernetes_pod
    - name: persistentvolumeclaim
      type: varchar
      unit: kubernetes_persistentvolumeclaim
    - name: persistentvolume
      type: varchar
      unit: kubernetes_persistentvolume
    - name: storageclass
      type: varchar
      unit: kubernetes_storageclass
    - name: persistentvolumeclaim_capacity_bytes
      type: double
      unit: bytes
    - name: persistentvolumeclaim_capacity_byte_seconds
      type: double
      unit: byte_seconds
    - name: volume_request_storage_byte_seconds
      type: double
      unit: byte_seconds
    - name: persistentvolumeclaim_usage_byte_seconds
      type: double
      unit: byte_seconds
    - name: persistentvolume_labels
      type: varchar
    - name: persistentvolumeclaim_labels
      type: varchar
  inputs:
    - name: ReportingStart
      type: time
    - default: hccm-openshift-persistentvolumeclaim
      name: PersistentVolumeClaimUsageReportName
      type: Report
  query: |
    SELECT report_period_start,
      report_period_end,
      interval_start,
      interval_end,
      namespace,
      pod,
      persistentvolumeclaim,
      persistentvolume,
      storageclass,
      persistentvolumeclaim_capacity_bytes,
      persistentvolumeclaim_capacity_byte_seconds,
      volume_request_storage_byte_seconds,
      persistentvolumeclaim_usage_byte_seconds,
      persistentvolume_labels,
      persistentvolumeclaim_labels
    FROM {| .Report.Inputs.PersistentVolumeClaimUsageReportName | reportTableName |}
    WHERE {| .Report.Inputs.PersistentVolumeClaimUsageReportName | reportTableName |}.interval_start >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}' - interval '10' day
