---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportDataSource
metadata:
  labels:
    cost-management: "true"
 name: kube-persistentvolume-labels
spec:
 prometheusMetricsImporter:
  query: |
   kube_persistentvolume_labels
