---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportDataSource
metadata:
  labels:
    cost-management: "true"
  name: kube-pod-labels
spec:
  prometheusMetricsImporter:
    query: |
      kube_pod_labels
  reportQueryView:
    queryName: kube-pod-labels
