---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportDataSource
metadata:
  labels:
    cost-management: "true"
 name: kube-pod-persistentvolumeclaim-info
spec:
 prometheusMetricsImporter:
  query: |
   kube_pod_spec_volumes_persistentvolumeclaims_info
