---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportDataSource
metadata:
  labels:
    cost-management: "true"
  name: kube-persistentvolumeclaim-labels
spec:
  prometheusMetricsImporter:
    query: |
      kube_persistentvolumeclaim_labels
