---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportDataSource
metadata:
  labels:
    cost-management: "true"
  name: persistentvolume-labels-raw
spec:
  reportQueryView:
    queryName: persistentvolume-labels-raw
