---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportQuery
metadata:
  name: "pod-labels-raw"
spec:
  reportDataSources:
    - "kube-pod-labels"
  columns:
    - name: pod
      type: string
      unit: kubernetes_pod
    - name: namespace
      type: string
      unit: kubernetes_namespace
    - name: labels
      type: map<string, string>
    - name: timestamp
      type: timestamp
      unit: date
    - name: dt
      type: string
  query: |
    SELECT labels['pod'] as pod,
        labels['namespace'] as namespace,
        labels,
        "timestamp",
        dt
    FROM {| dataSourceTableName "kube-pod-labels" |}
    WHERE element_at(labels, 'pod') IS NOT NULL
