apiVersion: metering.openshift.io/v1alpha1
kind: ReportQuery
metadata:
  name: pod-labels-raw
spec:
  reportQueryView:
    queryName: pod-labels-raw
  columns:
    - name: pod
      type: string
      unit: kubernetes_pod
    - name: namespace
      type: string
      unit: kubernetes_namespace
    - name: labels
      type: map<string, string>
    - name: timestamp
      type: timestamp
      unit: date
    - name: dt
      type: string
  inputs:
    - default: kube-pod-labels
      name: KubePodLabelsDataSourceName
      type: ReportDataSource
  query: |
    SELECT labels['pod'] as pod,
        labels['namespace'] as namespace,
        labels,
        "timestamp",
        dt
    FROM {| dataSourceTableName .Report.Inputs.KubePodLabelsDataSourceName |}
    WHERE element_at(labels, 'pod') IS NOT NULL
