---
- name: Converge
  hosts: all
  roles:
    - role: collect
      collect_delete_after: false
      collect_max_csvfile_size: 1
      collect_ocp_config_file: '/tmp/ocp-test-config.json'
      OCP_CLI: /usr/local/bin/oc
      OCP_CLUSTER_ID: 'bbb0b82b-e40d-41eb-8354-e07bc6a26a38'
      OCP_API: 'http://localhost:8001'
      METERING_API: 'http://localhost:8001'
      OCP_METERING_NAMESPACE: 'metering/test'
      OCP_TOKEN_PATH: '/tmp/collect-test-token'
