---
- name: Converge
  hosts: all
  roles:
    - role: collect
      collect_delete_after: false
      collect_ocp_config_file: '/tmp/ocp-test-config.json'
      collect_archive_format: bz2
      OCP_CLI: /usr/local/bin/oc
      collect_with_proxy: false
      OCP_CLUSTER_ID: 'bbb0b82b-e40d-41eb-8354-e07bc6a26a38'
