---
- name: Prepare
  hosts: all
  gather_facts: true
  vars:
    test_paths:
      - '/api/v1/reports/get'
  tasks:
    - name: install openshift client
      include_role:
        name: andrewrothstein.openshift-origin-client-tools

    - name: create symlink to simulate insights client
      file:
        path: '/usr/bin/insights-client'
        src: '/bin/true'
        state: link

    - name: create test setup.json
      copy:
        dest: '/tmp/ocp-test-config.json'
        content: '{"ocp_api":"http://localhost:8001", "metering_api":"http://localhost:8001", "ocp_token_file":"/tmp/collect-test-token", "ocp_cluster_id": "bbb0b82b-e40d-41eb-8354-e07bc6a26a38", "ocp_metering_namespace": "metering/test", "ocp_proxy_port": "8001", "ocp_validate_cert": "false"}'
        mode: '0644'

    - name: create test token file
      copy:
        dest: '/tmp/collect-test-token'
        content: '03d9687baa9d658f3a4be7aea73163118ad78569fbadf52fe893c3f3ab7c1777'

    - name: create test webserver dir
      file:
        path: "{{ item }}"
        state: directory
      with_items: "{{ test_paths }}"

    - name: create test file
      copy:
        dest: "{{ item }}/test"
        content: 'this,is,test,data'
      with_items: "{{ test_paths }}"

    - name: launch test web server
      shell: cd /tmp/www; nohup python -m SimpleHTTPServer 8001 </dev/null >/dev/null 2>&1 &
