---
# looping over blocks isn't available, so we'll loop over included tasks instead.
# see: https://github.com/ansible/ansible/issues/13262#issuecomment-335904803
- name: validate dependencies
  import_tasks: validate.yml
  vars:
    files:
      - '{{ collect_insights_client_cmd }}'
      - '{{ collect_ocp_config_file }}'

- name: Fetch OCP config file from remote host
  fetch:
    src: '{{ collect_ocp_config_file }}'
    dest: '/tmp/'
    fail_on_missing: true
    flat: true

- name: Read in OCP configuration file
  include_vars:
    file: '/tmp/{{ collect_ocp_config_file | basename }}'
    name: ocp_config

- name: validate ocp_config_file dependencies
  import_tasks: validate.yml
  vars:
    files:
      - '{{ ocp_config["ocp_token_file"] }}'

- name: Check for OC command-line
  stat:
    path: '{{ OCP_CLI }}'
  register: check_oc

- name: OCP_CLI does not exits
  fail:
    msg: 'No file was found for OCP_CLI at "{{ OCP_CLI }}".'
  when:
    - not check_oc.stat.exists

- name: Set facts from OCP config
  set_fact:
    ocp_validate_cert: '{{ ocp_config["ocp_validate_cert"] }}'
    ocp_metering_namespace: '{{ ocp_config["ocp_metering_namespace"] }}'

- name: Set facts from OCP config
  set_fact:
    ocp_insecure_login: '--insecure-skip-tls-verify={{ ocp_validate_cert }}'
    collect_endpoint_params: '?name={{ collect_report_name }}&format={{ collect_format }}&namespace={{ ocp_metering_namespace }}'
    collect_endpoint_path: 'api/v1/namespaces/{{ ocp_metering_namespace }}'
    collect_endpoint_url: '{{ ocp_config["ocp_api"] }}'

# conditional tag
- name: Define facts from OCP config with proxy
  set_fact:
    collect_endpoint_path: '{{ collect_endpoint_path }}/services/https:reporting-operator:http/proxy/api/v1/scheduledreports/get'
    collect_endpoint_url: '{{ collect_proxy_server_no_port }}:{{ ocp_config["ocp_proxy_port"] }}'
  tags: with_proxy

- name: Define OCP API URL without proxy
  set_fact:
    collect_endpoint_url: '{{ collect_endpoint_url }}/{{ collect_endpoint_path }}/{{ collect_endpoint_params }}'

- name: Create temp dir for downloaded files
  file:
    path: '{{ collect_download_path }}'
    state: directory

- name: Read the OCP token
  command: 'cat {{ ocp_config["ocp_token_file"] }}'
  register: cat_token
  changed_when: false

- name: Log in to OCP cluster
  command: '{{ OCP_CLI }} login {{ ocp_config["ocp_api"] }} {{ ocp_insecure_login }} --token {{ cat_token.stdout }}'
  when: cat_token.stdout is defined and cat_token != ''

- name: Run OC Proxy
  command: 'nohup {{ OCP_CLI }} proxy --port={{ ocp_config["ocp_proxy_port"] }} </dev/null >/dev/null 2>&1 &'
  async: 120
  poll: 0
  when: cat_token.stdout is defined and cat_token != ''
  tags: with_proxy

- name: Download OCP report from endpoint
  get_url:
    url: '{{ collect_endpoint_url }}'
    dest: '{{ collect_download_path }}/{{ collect_csv_uuid }}_openshift_usage_report.{{ collect_format }}'
    validate_certs: '{{ ocp_config["ocp_validate_cert"] | bool }}'
  register: download_result

- name: set csv_filename fact
  set_fact:
    collect_csv_filename: '{{ download_result.dest | basename }}'

- name: Generate archive manifest
  template:
    src: 'templates/manifest.j2'
    dest: '{{ collect_download_path }}/manifest.json'

- name: Create tarball
  archive:
    format: '{{ collect_archive_format }}'
    dest: '{{ collect_archive_path }}/{{ collect_archive_filename }}'
    path:
      - '{{ collect_download_path }}/manifest.json'
      - '{{ collect_download_path }}/{{collect_csv_filename}}'
    remove: '{{ collect_delete_after }}'
  register: archive_result

- name: Send payload to the Insights Client
  command: '{{ collect_insights_client_cmd }} --no-gpg --payload={{ collect_archive_path }}/{{ collect_archive_filename }} --content-type={{ collect_content_type }}'
  environment:
    BYPASS_GPG: 'True'
    EGG: '/etc/insights-client/rpm.egg'
  become: true
  when: archive_result.state == 'file'

- name: Remove temp files
  file:
    path: '{{ collect_download_path }}'
    state: absent
  when: collect_delete_after
