---
- name: Ensure needed variables are set
  fail:
    msg: 'You must supply "-e {{ item }}=<{{ item }}>".'
  when: 'item is not defined'
  with_items:
    - OCP_CLUSTER_ID

- name: Define OCP Usage configuration defaults
  set_fact:
    collect_ocp_config_file: '{{ collect_ocp_config_file_cluster_root }}/{{ OCP_CLUSTER_ID }}/{{ collect_ocp_config_filename }}'

- name: Define Cluster-unique config file name
  set_fact:
    collect_ocp_cluster_config_file: '/tmp/{{ OCP_CLUSTER_ID }}_{{ collect_ocp_config_file }}'

# looping over blocks isn't available, so we'll loop over included tasks instead.
# see: https://github.com/ansible/ansible/issues/13262#issuecomment-335904803
- name: validate dependencies
  import_tasks: validate.yml
  vars:
    files:
      - '{{ collect_insights_client_cmd }}'
      - '{{ collect_ocp_config_file }}'
  tags:
    - validate

- name: Fetch OCP config file from remote host
  fetch:
    src: '{{ collect_ocp_config_file }}'
    dest: '{{ collect_ocp_cluster_config_file }}'
    fail_on_missing: true
    flat: true

- name: Read in OCP configuration file
  include_vars:
    file: '{{ collect_ocp_cluster_config_file }}'
    name: ocp_config

- name: validate ocp_config_file dependencies
  import_tasks: validate.yml
  vars:
    files:
      - '{{ ocp_config["ocp_token_file"] }}'

- name: Set facts from OCP config
  set_fact:
    ocp_validate_cert: '{{ ocp_config["ocp_validate_cert"] }}'
    ocp_metering_namespace: '{{ ocp_config["ocp_metering_namespace"] }}'

- name: Set facts from OCP config
  set_fact:
    ocp_insecure_login: '--insecure-skip-tls-verify={{ ocp_validate_cert }}'
    api_host: '{{ ocp_config["ocp_api"] }}'
    api_path: '{{ ocp_config["metering_api"] }}/api/v1/reports/get'
    collect_file_prefix: '{{ collect_manifest_uuid }}'
    collect_manifest_uuid: '{{ collect_manifest_uuid }}'
    format: "&format={{ collect_format }}"
    namespace: "&namespace={{ ocp_metering_namespace }}"
    collect_config_path: '/tmp/{{ OCP_CLUSTER_ID }}_{{ collect_ocp_config_file | basename }}'
    OCP_CLI: ocp_config["ocp_cli"]

# getting a little clever to build lists to append into
- name: initialize fact lists
  set_fact:
    api_params: []
    api_urls: []
    csv_files: []

# this appends the string inside the brackets to the 'api_params' list.
- name: compile URL query params, append to param list
  set_fact:
    api_params: "{{ api_params + ['?name='+item+format+namespace] }}"
  with_items: "{{ collect_reports }}"

# this appends the string inside the brackets to the 'api_urls' list.
- name: assemble compiled URL facts, append to list.
  set_fact:
    api_urls: "{{ api_urls + [api_path+item] }}"
  with_items: "{{ api_params }}"

# Use a cluster specific path
- name: Set download_path
  set_fact:
    collect_cluster_download_path: '{{ collect_download_path }}/{{  OCP_CLUSTER_ID }}'

- name: Remove temp files
  file:
    path: '{{ collect_cluster_download_path }}'
    state: absent
  when: collect_delete_after

- name: Create temp dir for downloaded files
  file:
    path: '{{ collect_cluster_download_path }}'
    state: directory
    mode: 0777

- name: Read the OCP token
  command: 'cat {{ ocp_config["ocp_token_file"] }}'
  register: cat_token
  changed_when: false
  no_log: true

- name: Download OCP report from endpoint
  get_url:
    url: '{{ item }}'
    headers: "Authorization:Bearer {{ cat_token.stdout }}"
    dest: '{{ collect_cluster_download_path }}/{{ collect_file_prefix }}_openshift_usage_report.{{ idx }}.{{ collect_format }}'
    validate_certs: '{{ ocp_config["ocp_validate_cert"] | bool }}'
    timeout: '{{ collect_ocp_report_timeout }}'
  with_items: "{{ api_urls }}"
  loop_control:
    index_var: idx
  register: download_result

- name: append filename to fact list
  set_fact:
    csv_files: "{{ csv_files + [item.dest | basename] }}"
  with_items: "{{ download_result.results }}"

- name: Check that required files exist
  stat:
    path: '{{ collect_cluster_download_path + "/" + item }}'
  register: csv_stat_result
  with_items:
    - '{{ csv_files }}'

- name: Check for empty download results
  fail:
    msg: 'Downloaded file {{ item }} has no content or could not be found: {{ item.stat }}.'
  when: not item.stat.exists or (item.stat.exists and item.stat.size <= 0)
  with_items:
    - '{{ csv_stat_result.results }}'

- name: CSV filename to json
  set_fact:
    csv_files_json: "{{ csv_files | to_json }}"

- name: Generate archive manifest
  template:
    src: 'templates/manifest.j2'
    dest: '{{ collect_cluster_download_path }}/manifest.json'

- name: Create tarball
  archive:
    format: '{{ collect_archive_format }}'
    dest: '{{ collect_archive_path }}/{{ collect_archive_filename }}'
    path: "{{ collect_cluster_download_path }}"
    remove: '{{ collect_delete_after }}'
  register: archive_result

- name: Set Insights Client GPG Flag
  set_fact:
    collect_insights_bypass_gpg_flag: '--no-gpg'
  when:
    - collect_insights_bypass_gpg == 'True'

- name: Send payload to the Insights Client
  command: >-
    {{ collect_insights_client_cmd }} {{ collect_insights_bypass_gpg_flag }}
    --payload={{ collect_archive_path }}/{{ collect_archive_filename }}
    --content-type={{ collect_content_type }}

  environment:
    BYPASS_GPG: '{{ collect_insights_bypass_gpg }}'
    EGG: '{{ collect_insights_egg_path }}'
  become: true
  when: archive_result.state == 'file'

- name: Remove temp files
  file:
    path: '{{ collect_cluster_download_path }}'
    state: absent
  when: collect_delete_after

- name: Remove temp config
  file:
    path: '{{ collect_config_path }}'
    state: absent
  when: collect_delete_after

- name: Remove tarball
  file:
    path: '{{ collect_archive_path }}/{{ collect_archive_filename }}'
    state: absent
  when: collect_delete_after
